[build]
  functions = "functions"  # Path to your functions directory

[functions]
  # Specify external Node.js modules if needed
  external_node_modules = [
    "module-one",
    "module-two"
  ]

  # Set a custom timeout for functions
  timeout = 26  # Maximum timeout in seconds (up to 26)
