[build]
  functions = "functions"  # Path to your functions directory

[functions]
  node_bundler = "esbuild"  # Optional: Specify the bundler if needed
  # Set a custom timeout for functions
  timeout = 26  # Maximum timeout in seconds (up to 26)
